# Generated by Django 3.2.10 on 2022-02-24 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('hashtags', models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Ключевые навыки')),
                ('employment_type', models.SmallIntegerField(choices=[(0, 'Полная занятость'), (1, 'Неполная занятость'), (2, 'Стажировка')], db_index=True, default=0, verbose_name='Тип занятости')),
                ('experience', models.SmallIntegerField(choices=[(0, 'Без опыта'), (1, 'От 1 до 3 лет'), (2, 'От 3 до 6 лет'), (3, 'Более 6 лет')], db_index=True, default=0, verbose_name='Опыт работы')),
                ('salary', models.CharField(db_index=True, default='Не указана', max_length=30, verbose_name='Зарплата')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'Ожидает проверки'), (2, 'Опубликовано'), (3, 'Архивировано')], default=0, verbose_name='Статус')),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourites_vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
