# Generated by Django 3.2.10 on 2022-02-24 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        ('chat', '0002_chat_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.resume'),
        ),
    ]
