# Generated by Django 3.2.10 on 2022-02-24 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_auto_20220210_1623'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='мобильный телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('telegram', models.CharField(blank=True, max_length=64, verbose_name='аккаунт в "Telegram"')),
            ],
            options={
                'verbose_name': 'контакты',
                'verbose_name_plural': 'контакты',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(blank=True, db_index=True, null=True, verbose_name='ключевые навыки')),
                ('about', models.TextField(db_index=True, verbose_name='о себе')),
                ('portfolio', models.URLField(blank=True, null=True, verbose_name='ссылка на портфолио')),
            ],
            options={
                'verbose_name': 'опыт работы',
                'verbose_name_plural': 'опыт работ',
                'ordering': ('about',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=128, verbose_name='организация')),
                ('start', models.DateField(verbose_name='начало работы')),
                ('end', models.DateField(blank=True, null=True, verbose_name='окончание работы')),
                ('site', models.URLField(blank=True, verbose_name='сайт')),
                ('scope', models.CharField(max_length=64, verbose_name='сфера деятельности компании')),
                ('position', models.CharField(db_index=True, max_length=64, verbose_name='должность')),
                ('functions', models.TextField(blank=True, verbose_name='обязанности на рабочем месте')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.city', verbose_name='город')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'место работы',
                'verbose_name_plural': 'места работ',
                'ordering': ('organization',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(db_index=True, max_length=64, verbose_name='название должности')),
                ('salary', models.PositiveIntegerField(db_index=True, default=0, verbose_name='зарплата')),
                ('employment_type', models.SmallIntegerField(choices=[(0, 'Полная занятость'), (1, 'Неполная занятость'), (2, 'Стажировка')], db_index=True, default=0, verbose_name='Тип занятости')),
                ('relocation', models.SmallIntegerField(choices=[(0, 'невозможен'), (1, 'возможен'), (2, 'желателен')], default=0, verbose_name='переезд')),
                ('business_trip', models.SmallIntegerField(blank=True, choices=[(0, 'никогда'), (1, 'готов'), (2, 'иногда')], default=0, null=True, verbose_name='командировки')),
            ],
            options={
                'verbose_name': 'требования к должности',
                'verbose_name_plural': 'требования к должностям',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='название')),
                ('photo', models.ImageField(blank=True, upload_to='photos/', verbose_name='фотография')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ManyToManyField(blank=True, default=None, related_name='accepted_by', to=settings.AUTH_USER_MODEL)),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resumes.contacts', verbose_name='контакты')),
                ('experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resumes.experience', verbose_name='опыт работы')),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourites_resumes', to=settings.AUTH_USER_MODEL)),
                ('jobs', models.ManyToManyField(blank=True, default=None, related_name='jobs', to='resumes.Job', verbose_name='места работы')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resumes.position', verbose_name='должность/зарплата')),
                ('rejected_by', models.ManyToManyField(blank=True, default=None, related_name='rejected_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'резюме',
                'verbose_name_plural': 'резюме',
                'ordering': ('title',),
            },
        ),
    ]
