# Generated by Django 3.2.10 on 2022-02-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(db_index=True, default=False)),
                ('rejected', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
